server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
